name: Test

on: 
  workflow_dispatch:
    inputs:
      test_type:
        description: Choose test type
        required: true
        default: all
        type: choice
        options:
          - smoke
          - regression
          - all
  push:
    branches: [ main, master ]

permissions:
  contents: write
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  download-history:
    runs-on: ubuntu-latest
    name: Download history
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: gh-pages
          path: pages_history
      
      - name: Download existing pages
        if: always()
        run: |
          if [ -d "pages_history" ]; then
            echo "Found existing pages history"
            ls -la pages_history/
          else
            echo "No existing pages history found"
            mkdir -p pages_history
          fi
      
      - name: Store pages history
        uses: actions/upload-artifact@v4
        with:
          name: pages-history
          path: pages_history
          retention-days: 1

  test:
    runs-on: ubuntu-latest
    needs: download-history
    environment: github-pages
    
    steps:
      # выкачиваем репозиторий
      - uses: actions/checkout@v4
      
      # настраиваем java
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
      
      # Запускаем Selenoid напрямую
      - name: Start Selenoid
        run: |
          # Скачиваем и запускаем Selenoid
          curl -s https://aerokube.com/cm/bash | bash
          ./cm selenoid start --browsers 'chrome' --last-versions 1 --args "-limit 2"
          
          # Ждем запуска
          sleep 10
          
          # Проверяем статус
          curl -s http://localhost:4444/status || echo "Selenoid not ready yet"
          ps aux | grep selenoid || echo "Selenoid process not found"
      
      # запускаем тесты
      - name: Run tests
        env:
          CI: true
        run: |
          ./gradlew clean test -Dselenide.remote=http://localhost:4444/wd/hub --continue --no-daemon --info --stacktrace || true
          echo "=== Test Results ==="
          find build/reports/tests -name "*.html" -exec echo "Report: {}" \;
          echo "=== Allure Results ==="
          ls -la build/allure-results/ || echo "No Allure results"
      
      # генерируем отчет Allure
      - name: Generate Allure Report
        if: always()
        run: |
          ./gradlew allureReport
          echo "=== Allure Report Directory ==="
          ls -la build/reports/allure-report/ || echo "No Allure report"
      
      # Скачиваем историю страниц
      - name: Download pages history
        uses: actions/download-artifact@v4
        with:
          name: pages-history
          path: pages_history
      
      # Копируем историю в отчеты
      - name: Copy history to reports
        if: always()
        run: |
          if [ -d "pages_history" ] && [ -d "build/reports/allure-report" ]; then
            echo "Copying history to reports..."
            cp -r pages_history/* build/reports/allure-report/ || echo "Failed to copy history"
            ls -la build/reports/allure-report/
          else
            echo "No history to copy or no reports generated"
          fi
      
      # Сохраняем отчеты как артефакт
      - name: Store Allure report
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: allure-report
          path: build/reports/allure-report
          retention-days: 1
      
      # Очищаем Selenoid
      - name: Cleanup
        if: always()
        run: |
          ./cm selenoid stop || true
          pkill -f selenoid || true

  publish-report:
    runs-on: ubuntu-latest
    needs: test
    name: Report publication
    environment: github-pages
    
    steps:
      # Скачиваем отчеты
      - name: Download Allure report
        uses: actions/download-artifact@v4
        with:
          name: allure-report
          path: allure-report
      
      # Обновляем ветку gh-pages
      - name: Update gh-pages branch
        run: |
          # Настраиваем git
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          
          # Скачиваем ветку gh-pages
          git fetch origin gh-pages
          git checkout gh-pages
          
          # Очищаем ветку (кроме .git)
          find . -not -path './.git*' -not -path '.' -delete
          
          # Копируем отчеты Allure в корень
          cp -r allure-report/* . || echo "Failed to copy reports"
          
          # Добавляем .nojekyll файл
          echo "# GitHub Pages" > .nojekyll
          
          # Проверяем содержимое
          ls -la
          echo "=== Checking for index.html ==="
          ls -la index.html || echo "index.html not found!"
          
          # Коммитим изменения
          git add .
          git commit -m "Update Allure reports $(date)" || echo "No changes to commit"
          
          # Пушим изменения
          git push origin gh-pages --force
      
      # настраиваем GitHub Pages
      - name: Setup Pages
        uses: actions/configure-pages@v4
        if: always()
      
      # загружаем артефакт для GitHub Pages
      - name: Deploy to GitHub Pages
        uses: actions/upload-pages-artifact@v3
        if: always()
        with:
          path: './allure-report'
      
      # публикуем отчет на GitHub Pages
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
        if: always()
